### ISSUE TITLE
Crash when using a different scene

### ISSUE THREAD

**Issue by Mabadman** [padiix/RecORDER#3] opened 2024-07-14 19:53 UTC
**Describe the bug**
OBS will crash if a recording is made using a new scene.

**To Reproduce**
1. Create a scene. In my case scene 1 has Game Capture (any fullscreen), Display Capture, and a couple Application Audio Capture sources (this is from a plugin).
2. Create another scene. In my case it only has 1 Game Capture (any fullscreen)
3. Start recording (or start replay buffer)
4. End recording (or save replay buffer). OBS will crash. 

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Plugins: [No Prevent Sleep](https://github.com/Meachamp/OBS-NoPreventSleep), Application Audio Capture, Advanced Scene Switcher (no scene switching rules were active when testing)
Scripts: [Beep on replay buffer save.lua](https://gist.github.com/snakecase/e816384a071cec31efbb4b9e429c108d)
Crash Log: [crashlog.txt](https://github.com/user-attachments/files/16228611/crashlog.txt)

**Comment by padiix** [comment] 2024-07-14 20:12
Hello @Mabadman , I'll try to reproduce the bug in the following week and get back to you if I am unable to do so.

**Comment by padiix** [comment] 2024-07-15 11:43
Alright, I was able to reproduce it only with the recording, but I do have some idea of what can be the issue. 

For the basic gist of what is happening in the code:
- The script checks if the source (ex. Game Capture) exists using the UUID ([Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier))
  

> At the time of writing the script I thought it would be the best way to combat sources with same names (technically the same name sources are impossible, but there are some scripts that allow you to do that)

- Because the scenes work like different environments, it cannot find the source by UUID 
- Because I did not give an exception to this behavior it crashes the OBS

I'll try to find some time to fix this in the following weeks, but I'll keep this issue closed until I actually fix it.

> For now try to remember to **always refresh the sources in the script** if you switch scenes.

Thank you for bringing this to my eyes!

**Comment by padiix** [comment] 2024-07-20 17:36
The issue was resolved in version 1.3.1. 
The main way I wanted to go with fixing it was too hard for me to implement for now, so I will be working on it in the shadows.

I did create a quickfix for the issue you presented, but be aware, that every time you use a different scene, you will need to re-select the source until I create a permament fix, which is not too easy for me 😅

**Closed by padiix** 2024-07-20 17:36 UTC
Labels: bug, good first issue

**Comment by Mabadman** [comment] 2024-07-20 19:23
No problem. Thanks for taking your time
